### ISSUE TITLE
Implement preact

### ISSUE THREAD

**Issue by ronnygunawan** [teknologi-umum/decimal-clock#38]
Reference: https://preactjs.com/

**Comment by keshavgbpecdelhi** [comment]
Not sure were to implement, as a good first issue can you guide me what to do.

**Comment by elianiva** [comment]
@keshavgbpecdelhi 

- fork the repo, clone it
- create a folder called `preact`
- [see here](https://preactjs.com/guide/v10/getting-started) to scaffold a preact project
- since preact is just react but smaller, you can use the [existing react](https://github.com/teknologi-umum/decimal-clock/tree/main/react-hooks) version in this repo for reference
